### ISSUE TITLE
Nuget package?

### ISSUE THREAD

**Issue by pmarflee** [leung85/AspNetCore.Identity.LiteDB#2]
I'm interested in using this library in a project I'm working on.  However it doesn't look as if any Nuget package is available for it.

It would be useful if this library was made available for download via Nuget.

**Comment by mwkldeveloper** [comment]
@pmarflee 
For your request, I create a Nuget package:
[https://www.nuget.org/packages/MWKL.AspNetCore.Identity.LiteDB/](https://www.nuget.org/packages/MWKL.AspNetCore.Identity.LiteDB/)

Btw, friendly reminders, this project is just copy from [https://github.com/fabian-blum/AspNetCore.Identity.LiteDB](https://github.com/fabian-blum/AspNetCore.Identity.LiteDB)
for update to support core 3.1 and liteDb 5

As the origin Author fabian-blum seems not maintain the project, so i copy one to update, if origin Author return to maintain the project, please and better use his version.
